spring.application.name=studentDemo
spring.datasource.url=removedForSecurity
spring.datasource.username=removedForSecurity:)
spring.datasource.password=sameHere:)
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true